app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# Customizations
admin.site.site_header = 'Welcome to ECHO Interoperabilty administration'
admin.site.site_title = 'Echo epts'
admin.site.index_title = 'Login to Echo Interobily'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/urls.py
from django.urls import path
from core.views import IndexView, ArtOptimizationListView
from core import views


app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('art-optimization/', ArtOptimizationListView.as_view(), name='art-optimization'),
    # path('cheque/cancelado/', ChequeCanceladoListView.as_view(), name='cheque-cancelado'),
    # path('cheque/relatorio/', GenerateChequePDF.as_view(), name='cheque-relatorio'),
    # path('cheque/regularizado/', ChequeRegularizadoListView.as_view(), name='cheque-regularizado'),
    # path('cheque-regularizado/relatorio/', GenerateChequeRegularizadoPDF.as_view(), name='cheque-regularizado-relatorio'),
    # path('cheque-cancelado/relatorio/', GenerateChequeCanceladoPDF.as_view(), name='cheque-cancelado-relatorio'),
    # path('celery/', views.celery, name='celery'),
    # path('emitente/relatorio', GenerateEmitentePDF.as_view(), name='emitente-relatorio'),
    # path('emitente/create', views.EmitenteCreateView, name='emitente'),
   ]

app/core/models.py
from django.db import models
from django.db.models.fields import DateField
from django.db.models.signals import pre_save, post_save
from core.utils.constants import Constants


MES = (
    ('Jan', 'Janeiro'),
    ('Feb', 'Fevereiro'),
    ('Mar', 'Março'),
    ('Apr', 'Abril'),
    ('May', 'Maio'),
    ('Jun', 'Junho'),
    ('Jul', 'Julho'),
    ('Aug', 'Agosto'),
    ('Sep', 'Setembro'),
    ('Oct', 'Outubro'),
    ('Nov', 'Novembro'),
    ('Dec', 'Dezembro')
)

class Province(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class District(models.Model):
    """Model definition for District."""

    # TODO: Define fields here
    name = models.CharField(max_length=100)
    province = models.ForeignKey('Province', on_delete=models.CASCADE)
   
    def __str__(self):
        """Unicode representation of District."""
        return self.name

class HealthFacility(models.Model):
    """Model definition for HealthFacility."""
    id = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255)
    # openmrs_name = models.CharField(max_length=255, null=True, blank=True)
    district = models.ForeignKey('District', on_delete=models.CASCADE)

    class Meta:
        """Meta definition for HealthFacility."""

        verbose_name = 'Health Facility'
        verbose_name_plural = 'Health Facilities'

    def __str__(self):
        """Unicode representation of HealthFacility."""
        return self.name

# class OpenmrsOptimization(models.Model):
#     hf = models.ForeignKey(HealthFacility, on_delete=models.CASCADE)
#     period = models.CharField(max_length=10)
#     em_tarv = models.IntegerField()
#     elegiveislpvr_geral = models.IntegerField()    
#     elegiveis_lpvr = models.IntegerField()    
#     elegiveisdtg_geral = models.IntegerField()    
#     elegiveisdtg = models.IntegerField()    
#     dtg_geral = models.IntegerField()    
#     dtg = models.IntegerField()    
#     lpvr_geral = models.IntegerField()    
#     lpvr = models.IntegerField()
#     synced = models.BooleanField(default=False)
    
    
    # class Meta: 
    #     verbose_name = 'Openmrs Optimization' 
    #     verbose_name_plural = 'Openmrs Optimizations'   
        
    # def __str__(self):
    #     return f'{self.hf.name} {self.period}'
    
class DataSet(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=500, null=True, blank=True)
    
    
    def __str__(self):
        return self.name

# class DataSetValue(models.Model):
#     period = models.CharField(max_length=200)
#     period_description = models.CharField(max_length=100, null=True, blank=True)
#     completeDate = models.DateTimeField(auto_now=True)
#     orgUnit = models.ForeignKey('HealthFacility', on_delete=models.CASCADE)
#     dataSet = models.ForeignKey(DataSet, on_delete=models.CASCADE)
    

#     def __str__(self):
#         return f'{self.dataSet.name} {self.period}'
    
# Signal to insert period field based on data entered 
# def insert_period_desc(sender, instance, created, *args, **kwargs):
#     if created:
#         dataSet = DataSet.objects.get(id=instance.id)
#         year = str(dataSet.period[0:4])
#         month = str(dataSet.period[4:7])
#         month_desc = months[month]
#         dataSet.period_description = f'{year} {month_desc}'
#         dataSet.save()
       

# post_save.connect(insert_period_desc, sender=DataSet)

class DataElement(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=500, null=True, blank=True)
    openmrs = models.CharField(max_length=100, null=True, blank=True)
    categoryOptionCombo = models.CharField(max_length=200, null=True, blank=True)
    attributeOptionCombo = models.CharField(max_length=200, null=True, blank=True)
    dataSet = models.ForeignKey(DataSet, on_delete=models.CASCADE)
 
    
    def __str__(self):
        return self.name

class DataElementValue(models.Model):
    period = models.CharField(max_length=100)
    value = models.IntegerField(null=True, blank=True) 
    healthFacility = models.ForeignKey(HealthFacility, on_delete=models.CASCADE)
    dataElement = models.ForeignKey('DataElement', on_delete=models.CASCADE)
    synced = models.BooleanField(default=False)
    
    def __str__(self):
        return self.dataElement.name
    
class OpenmrsURL(models.Model): 
    province = models.CharField(max_length=100)
    instance_name = models.CharField(max_length=100)
    uuid = models.CharField(max_length=255)
    url = models.CharField(max_length=500)
    dataSet = models.ForeignKey(DataSet, on_delete=models.CASCADE, null=True, blank=True)
    
    
    def __str__(self):
        return f'{self.province} {self.instance_name}'
    
class PeriodDescription(models.Model):
    ano = models.CharField(max_length=10)
    mes = models.CharField(max_length = 50, choices=MES)
    period_ref = models.CharField(max_length=100, null=True, blank=True)
    period = models.CharField(max_length=50, null=True, blank=True)
    
    def __str__(self):
        return str(self.period_ref)
    
def create_ref_and_period(sender, instance, created, *args, **kwargs): 
    if created:
        constants = Constants()
        key_list = list(constants.get_months().keys())
        val_list = list(constants.get_months().values())
        obj = PeriodDescription.objects.get(id=instance.id)
        obj.period_ref = f'{obj.mes} {obj.ano}'
        mes_ref = obj.mes
        obj.period = f'{obj.ano}{key_list[val_list.index(mes_ref)]}'
        obj.save()
        
post_save.connect(create_ref_and_period, sender=PeriodDescription)   


class TestUS(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

app/core/forms.py
from django import forms
from django.utils.translation import ugettext as _

from core.models import DataElementValue

class ArtOptimizationForm(forms.ModelForm):
    class Meta:
        model = DataElementValue
        fields = ( 'period', 'value', 'healthFacility', 'dataElement', 'synced') 
        
        label = {     
            'period': _('Period'),
            'value': _('Valor'),
            'healthFacility': _('Health Facility'),
            'dataElement': _('Data Element'),  
            'synced': _('Synced'),
        }

app/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.views.generic import TemplateView, ListView, CreateView, UpdateView, View

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


from core.forms import ArtOptimizationForm

from core.models import Province, District, HealthFacility, DataSet, DataElementValue

from django.template.loader import get_template


class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'optimization_list'
    model = DataElementValue

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        # context['cheque_devolvido'] = Cheque.objects.all().count()
        # context['cheque_cancelado'] = Cheque.objects.filter(estado_cheque='Cancelado').count()
        # context['cheque_regularizado'] = Cheque.objects.filter(estado_cheque='Regularizado').count()

        return context

    def get_queryset(self):
        return DataElementValue.objects.all()
    
class ArtOptimizationListView(ListView):
    template_name = 'artoptimization_list.html'
    context_object_name = 'filtered_data'
    queryset = DataElementValue.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(ArtOptimizationListView, self).get_context_data(**kwargs)
        context['period'] = DataElementValue.objects.all()

app/core/templates/layouts/base.html
<!DOCTYPE HTML>
<html>
<head>
{% load static %}
<title>{% block title %}Echo Interoperability Middleware{% endblock title %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content=ECHO" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static 'css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
<!-- jQuery -->
<link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css'>
<!-- lined-icons -->
<link rel="stylesheet" href="{% static 'css/icon-font.min.css' %}" type='text/css' />
<!-- //lined-icons -->
<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'js/amcharts.js' %}"></script>	
<script src="{% static 'js/serial.js' %}"></script>	
<script src="{% static 'js/light.js' %}"></script>	
<script src="{% static 'js/radar.js' %}"></script>	
<link href="{% static 'css/barChart.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'css/fabochart.css' %}" rel='stylesheet' type='text/css' />
<!-- Date Time Picker CSS -->
  <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui.css' %}">
  <link rel='stylesheet' href="{% static 'date-time-phone/jquery-ui-timepicker-addon.css' %}" />
<!-- Date Time Picker CSS -->

<!--clock init-->
<script src="{% static 'js/css3clock.js' %}"></script>
<!--Easy Pie Chart-->
<!--skycons-icons-->
<script src="{% static 'js/skycons.js' %}"></script>

 <!-- Date Time Picker JS -->
  <script src="{% static 'date-time-phone/jquery-ui.js' %}" ></script>
  <script src="{% static 'date-time-phone/jquery-ui-timepicker-addon.js' %}"></script> 

<script src="{% static 'js/jquery.easydropdown.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>



<!--//skycons-icons-->
</head> 
<body>
<div class="page-container">
<!--/content-inner-->
<div class="left-content">
	<div class="inner-content">
	<!-- header-starts -->
	<div class="header-section">
				<!--menu-right-->
				<div class="top_menu">
						<div class="main-search">
									<form>
										<input type="text" value="Search" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'Search';}" class="text"/>
										<input type="submit" value="">
									</form>
							<div class="close"><img src="{% static 'images/cross.png' %}" /></div>
						</div>
							<div class="srch"><button></button></div>
							<script type="text/javascript">
									$('.main-search').hide();
								$('button').click(function (){
									$('.main-search').show();
									$('.main-search text').focus();
								}
								);
								$('.close').click(function(){
									$('.main-search').hide();
								});
							</script>
					<!--/profile_details-->
						<div class="profile_details_left">
							<ul class="nofitications-dropdown">
									<li class="dropdown note">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope-o"></i> <span class="badge">3</span></a>
									</li>

										
								
					<li class="dropdown note">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-bell-o"></i> <span class="badge">5</span></a>

					</li>	
				<li class="dropdown note">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-tasks"></i> <span class="badge blue1">9</span></a>
								
					</li>		   							   		
					<div class="clearfix"></div>	
						</ul>
					</div>
					<div class="clearfix"></div>	
					<!--//profile_details-->
				</div>
				<!--//menu-right-->
			<div class="clearfix"></div>
		</div>
			
	{% block content %}
	{% endblock content %}
										
	<footer>
		<p>&copy 2021 Abt Associates Inc. All Rights Reserved</a></p>
	</footer>
<!--footer section end-->
    </div>
</div>
				<!--//content-inner-->
			<!--/sidebar-menu-->
				<div class="sidebar-menu">
					<header class="logo">
					<a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span> </a> <a href="{% url 'core:index' %}"> <span id="logo"> <h1>ECHO</h1></span> 
					<!--<img id="logo" src="" alt="Logo"/>--> 
				  </a> 
				</header>
<div style="border-top:1px solid rgba(69, 74, 84, 0.7)"></div>
<!--/down-->
				<div class="down">	
							<a href="index.html"><img src={{request.profile.imageURL}}></a>
							<a href="index.html"><span class=" name-caret">Xavier</span></a>
							<p></p>
						<ul>
						<li><a class="tooltips" href="index.html"><span>Perfil</span><i class="lnr lnr-user"></i></a></li>
							<li><a class="tooltips" href="index.html"><span>Definicoes</span><i class="lnr lnr-cog"></i></a></li>
							<li><a class="tooltips" href=""><span>Sair</span><i class="lnr lnr-power-switch"></i></a></li>
							</ul>
						</div>
					<!--//down-->
				<div class="menu">
						<ul id="menu" >
							
								<li id="menu-academico" ><a href="#"><i class="fa fa-file-text-o"></i> <span>ART Optimization</span> <span class="fa fa-angle-right" style="float: right"></span></a>
									<ul id="menu-academico-sub" >
									<li id="menu-academico-boletim" ><a href="{% url 'core:art-optimization' %}">Listar</a></li>
									</ul>
								</li>
						
						<li id="menu-academico" ><a href="#"><i class="lnr lnr-book"></i> <span>TX_CURR</span> <span class="fa fa-angle-right" style="float: right"></span></a>
								<ul id="menu-academico-sub" >
								<li id="menu-academico-avaliacoes" ><a href="">Listar</a></li>
					
								</ul>
							</li>
							
						<li id="menu-academico" ><a href="#"><i class="lnr lnr-layers"></i> <span>TX_NEW</span> <span class="fa fa-angle-right" style="float: right"></span></a>
								<ul id="menu-academico-sub" >
								<li id="menu-academico-avaliacoes" ><a href="">Listar</a></li>

								</ul>
							</li>
						<li><a href="chart.html"><i class="lnr lnr-chart-bars"></i> <span>TX_ML</span> <span class="fa fa-angle-right" style="float: right"></span></a>
							    <ul id="menu-academico-sub" >
								<li id="menu-academico-avaliacoes" ><a href="">Listar</a></li>
						</ul>
						</li>
						<li id="menu-academico" ><a href="#"><i class="lnr lnr-layers"></i> <span>TX_PVLS</span> <span class="fa fa-angle-right" style="float: right"></span></a>
								<ul id="menu-academico-sub" >
								<li id="menu-academico-avaliacoes" ><a href="">Listar</a></li>

								</ul>
							</li>
						<li><a href="chart.html"><i class="lnr lnr-chart-bars"></i> <span>CXCA_TX</span> <span class="fa fa-angle-right" style="float: right"></span></a>
							    <ul id="menu-academico-sub" >
								<li id="menu-academico-avaliacoes" ><a href="">Listar</a></li>
						</ul>
						<li id="menu-academico" ><a href="#"><i class="lnr lnr-layers"></i> <span>TX_RTT</span> <span class="fa fa-angle-right" style="float: right"></span></a>
							<ul id="menu-academico-sub" >
							<li id="menu-academico-avaliacoes" ><a href="">Listar</a></li>

							</ul>
						</li>
					<li><a href="chart.html"><i class="lnr lnr-chart-bars"></i> <span>TX_TB and TB_PREV</span> <span class="fa fa-angle-right" style="float: right"></span></a>
							<ul id="menu-academico-sub" >
							<li id="menu-academico-avaliacoes" ><a href="">Listar</a></li>
					</ul>
					<li id="menu-academico" ><a href="#"><i class="lnr lnr-layers"></i> <span>IMER</span> <span class="fa fa-angle-right" style="float: right"></span></a>
						<ul id="menu-academico-sub" >
						<li id="menu-academico-avaliacoes" ><a href="">Listar</a></li>

						</ul>
					</li>
				<li><a href="chart.html"><i class="lnr lnr-chart-bars"></i> <span>DSD</span> <span class="fa fa-angle-right" style="float: right"></span></a>
						<ul id="menu-academico-sub" >
						<li id="menu-academico-avaliacoes" ><a href="">Listar</a></li>
				</ul>
						</ul>
					</div>
					</div>
					<div class="clearfix"></div>		
				</div>
				<script>
				var toggle = true;
							
				$(".sidebar-icon").click(function() {                
					if (toggle)
					{
					$(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
					$("#menu span").css({"position":"absolute"});
					}
					else
					{
					$(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
					setTimeout(function() {
						$("#menu span").css({"position":"relative"});
					}, 400);
					}
								
								toggle = !toggle;
							});

<!--js -->
<link rel="stylesheet" href="css/vroom.css">
<script type="text/javascript" src="js/vroom.js"></script>
<script type="text/javascript" src="js/TweenLite.min.js"></script>
<script type="text/javascript" src="js/CSSPlugin.min.js"></script>
<script src="js/jquery.nicescroll.js"></script>
<script src="js/scripts.js"></script>
<script type="text/javascript" src="js/tipo.js"></script>

<!-- Bootstrap Core JavaScript -->
   <script src="js/bootstrap.min.js"></script>

<script>
    $( function() {

        $( "#id_data_devolucao" ).datepicker({ dateFormat: 'dd-mm-yy' }).attr("autocomplete", "off") 
    });
  </script>
  <!-- Date Time Picker JS -->

  <!-- Phone Mask JS -->
  <script src="{% static 'date-time-phone/jquery-input-mask-phone-number.min.js' %}"></script> 

  <script>
    //(xxx) xxx-xxxx format code
    $(document).ready(function () {
        $('#id_telefone_1').usPhoneFormat({
            format: '(xxx) xx-xxxxxxx',
        })   
    });
  </script>
  <!-- Phone Mask JS -->

</body>
</html>

app/core/templates/layouts/base1.html
     
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
<title>{% block title %}Sistema de gestao de cheques devolvidos{% endblock title %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Sistema de gestao de cheques devolvidos" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!-- Bootstrap Core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet"> 
<!-- jQuery -->
<link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css'>
<!-- lined-icons -->
<link rel="stylesheet" href="{% static 'css/icon-font.min.css' %}" type='text/css' />
<!-- //lined-icons -->
<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'js/amcharts.js' %}"></script>	
<script src="{% static 'js/serial.js' %}"></script>	
<script src="{% static 'js/light.js' %}"></script>	
<script src="{% static 'js/radar.js' %}"></script>	
<link href="{% static 'css/barChart.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'css/fabochart.css' %}" rel='stylesheet' type='text/css' />
<!--clock init-->
<script src="{% static 'js/css3clock.js' %}"></script>
<!--Easy Pie Chart-->
<!--skycons-icons-->
<script src="{% static 'js/skycons.js' %}"></script>

<script src="{% static 'js/jquery.easydropdown.js' %}"></script>

<!--//skycons-icons-->
</head> 
<body>
   <div class="page-container">
   <!--/content-inner-->
	<div class="left-content">
	   <div class="inner-content">
		{% include 'layouts/header.html' %}
{% block content %}

{% endblock content %}

app/core/templates/layouts/footer.html
<!--footer section start-->
<footer>
    <p>&copy 2020 Fincode . Todos os direitos reservados | Desenvolvido pela Fincode</p>
</footer>
<!--footer section end-->

app/core/templates/layouts/sidebar.html
<!--/sidebar-menu-->
{% load static %}
<div class="sidebar-menu">
<header class="logo">
<a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span> </a> <a href="index.html"> <span id="logo"> <h1>SIGC</h1></span> 
<!--<img id="logo" src="" alt="Logo"/>--> 
</a> 
</header>
<div style="border-top:1px solid rgba(69, 74, 84, 0.7)"></div>
<!--/down-->
<div class="down">	
			<a href="index.html"><img src="{% static 'images/admin.jpg' %}"></a>
			<a href="index.html"><span class=" name-caret">Ana Fulana</span></a>
			<p>Administrador de Sistemas</p>
		<ul>
		<li><a class="tooltips" href="index.html"><span>Perfil</span><i class="lnr lnr-user"></i></a></li>
			<li><a class="tooltips" href="index.html"><span>Configuracoes</span><i class="lnr lnr-cog"></i></a></li>
			<li><a class="tooltips" href="index.html"><span>Sair</span><i class="lnr lnr-power-switch"></i></a></li>
			</ul>
		</div>
	<!--//down-->
<div class="menu">
		<ul id="menu" >
			<li><a href="index.html"><i class="fa fa-tachometer"></i> <span>Dashboard</span></a></li>
				<li id="menu-academico" ><a href="#"><i class="fa fa-table"></i> <span> Tabs &amp; Panels</span> <span class="fa fa-angle-right" style="float: right"></span></a>
				<ul id="menu-academico-sub" >
				<li id="menu-academico-avaliacoes" ><a href="tabs.html"> Tabs &amp; Panels</a></li>
				<li id="menu-academico-boletim" ><a href="widget.html">Widgets</a></li>
				<li id="menu-academico-avaliacoes" ><a href="calender.html">Calendar</a></li>
				
				</ul>
			</li>
				<li id="menu-academico" ><a href="#"><i class="fa fa-file-text-o"></i> <span>Ui Elements</span> <span class="fa fa-angle-right" style="float: right"></span></a>
					<ul id="menu-academico-sub" >
					<li id="menu-academico-avaliacoes" ><a href="forms.html">Forms</a></li>
					<li id="menu-academico-boletim" ><a href="validation.html">Validation Forms</a></li>
					<li id="menu-academico-boletim" ><a href="table.html">Tables</a></li>
					<li id="menu-academico-boletim" ><a href="buttons.html">Buttons</a></li>
					</ul>
				</li>
		<li><a href="typography.html"><i class="lnr lnr-pencil"></i> <span>Typography</span></a></li>
		<li id="menu-academico" ><a href="#"><i class="lnr lnr-book"></i> <span>Pages</span> <span class="fa fa-angle-right" style="float: right"></span></a>
				<ul id="menu-academico-sub" >
				<li id="menu-academico-avaliacoes" ><a href="login.html">Login</a></li>
				<li id="menu-academico-boletim" ><a href="register.html">Register</a></li>
				<li id="menu-academico-boletim" ><a href="404.html">404</a></li>
				<li id="menu-academico-boletim" ><a href="sign.html">Sign up</a></li>
				<li id="menu-academico-boletim" ><a href="profile.html">Profile</a></li>
				</ul>
			</li>
			<li><a href="#"><i class="lnr lnr-envelope"></i> <span>Mail Box</span><span class="fa fa-angle-right" style="float: right"></span></a>
			<ul>
			<li><a href="inbox.html"><i class="fa fa-inbox"></i> Inbox</a></li>
			<li><a href="compose.html"><i class="fa fa-pencil-square-o"></i> Compose Mail</a></li>
			<li><a href="editor.html"><span class="lnr lnr-highlight"></span> Editors Page</a></li>
		
			</ul>
		</li>
		<li id="menu-academico" ><a href="#"><i class="lnr lnr-layers"></i> <span>Components</span> <span class="fa fa-angle-right" style="float: right"></span></a>
				<ul id="menu-academico-sub" >
				<li id="menu-academico-avaliacoes" ><a href="grids.html">Grids</a></li>
				<li id="menu-academico-boletim" ><a href="media.html">Media Objects</a></li>

				</ul>
			</li>
		<li><a href="chart.html"><i class="lnr lnr-chart-bars"></i> <span>Charts</span> <span class="fa fa-angle-right" style="float: right"></span></a>
			<ul>
			<li><a href="map.html"><i class="lnr lnr-map"></i> Maps</a></li>
			<li><a href="graph.html"><i class="lnr lnr-apartment"></i> Graph Visualization</a></li>
		</ul>
		</li>
		<li id="menu-comunicacao" ><a href="#"><i class="fa fa-smile-o"></i> <span>More</span><span class="fa fa-angle-double-right" style="float: right"></span></a>
			<ul id="menu-comunicacao-sub" >
			<li id="menu-mensagens" style="width:120px" ><a href="project.html">Projects <i class="fa fa-angle-right" style="float: right; margin-right: -8px; margin-top: 2px;"></i></a>
				<ul id="menu-mensagens-sub" >
				<li id="menu-mensagens-enviadas" style="width:130px" ><a href="ribbon.html">Ribbons</a></li>
				<li id="menu-mensagens-recebidas"  style="width:130px"><a href="blank.html">Blank</a></li>
				</ul>
			</li>
			<li id="menu-arquivos" ><a href="500.html">500</a></li>
			</ul>
		</li>
		</ul>
	</div>
	</div>
	<div class="clearfix"></div>		
</div>
<script>
var toggle = true;
			
$(".sidebar-icon").click(function() {                
	if (toggle)
	{
	$(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
	$("#menu span").css({"position":"absolute"});
	}
	else
	{
	$(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
	setTimeout(function() {
		$("#menu span").css({"position":"relative"});
	}, 400);
	}
				
				toggle = !toggle;
			});
</script>
<!--js -->